# -*- coding: utf-8 -*-
"""Entrenamiento_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWBSxHeLG1__ljI-UrU6eJw5qcXWb_Rx
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="3Sradtl6pLSQsrNU0VYC")
project = rf.workspace("tanias-workspace-nhc7a").project("imissnwjns")
version = project.version(3)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    name='yolov8_puzzlebot_signs_v2'
)

metrics = model.val()

print("\n=== MODEL SUMMARY ===")
model.info()

print("\n=== MÉTRICAS DE PRECISIÓN ===")
print(f"mAP50: {metrics.box.map50:.4f}")
print(f"mAP50-95: {metrics.box.map:.4f}")
print(f"Precisión (Precision): {metrics.box.mp:.4f}")
print(f"Exhaustividad (Recall): {metrics.box.mr:.4f}")

import zipfile
import os
from google.colab import files

def zip_folder(folder_path, output_path):
    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files_in_dir in os.walk(folder_path):
            for file in files_in_dir:
                relative_path = os.path.relpath(os.path.join(root, file), os.path.dirname(folder_path))
                zipf.write(os.path.join(root, file), relative_path)

folder_to_zip = 'runs'
zip_filename = 'resultados_yolov8_robot_v2.zip'

print("Comprimiendo carpeta de resultados")
zip_folder(folder_to_zip, zip_filename)
print(f"Archivo creado: {zip_filename}")

print("Iniciando descarga")
files.download(zip_filename)